name: CI - build, test, scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install backend deps
        run: |
          cd backend
          npm ci

      - name: Install frontend deps
        run: |
          cd frontend
          npm ci

      - name: Run backend lint & tests
        run: |
          cd backend
          npm run lint
          npm test

      - name: Run frontend lint & tests
        run: |
          cd frontend
          npm run lint
          npm test

      - name: Dependency scan (backend)
        uses: aquasecurity/trivy-action@v1
        with:
          scan-type: 'fs'
          path: 'backend'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1'

      - name: Dependency scan (frontend)
        uses: aquasecurity/trivy-action@v1
        with:
          scan-type: 'fs'
          path: 'frontend'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1'

      - name: Build docker image
        run: |
          docker build -t todo-app:${{ github.sha }} .

      - name: Scan docker image
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: 'todo-app:${{ github.sha }}'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
